controllers:
  resource: ../src/Controller/HomeController.php
  type: attribute

generation:
  path: /generation
  controller: App\Controller\GenerationController::index

list:
  path: /list
  controller: App\Controller\ListController::list

personnage:
  path: /perso
  controller: App\Controller\PersonnageController::show
